version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/go"
  schedule:
    interval: "weekly"
- package-ecosystem: "cargo"
  directory: "/rust"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/nodejs"
  schedule:
    interval: "weekly"